name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username x-access-token --password-stdin
          docker build -t docker.pkg.github.com/vegarn/googvarm/frontend:${GITHUB_SHA:0:8} .

      - name: push
        run: |
          docker push docker.pkg.github.com/vegarn/googvarm/frontend:${GITHUB_SHA:0:8}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: deploy
        run: |
          echo deploy

